ngtv_words <- readLines("negative-words.txt")
head(ngtv_words)
library(rvest)
library(XML)
library(magrittr)
corpus <- ngtv_words
corpus <- Corpus(VectorSource(corpus))
inspect(corpus[1:10])
corpus <- tm_map(corpus, tolower)
corpus <- tm_map(corpus, removePunctuation)
corpus <- tm_map(corpus, removeNumbers)
corpus <- tm_map(corpus, stripWhitespace)
inspect(corpus[1:10])
cleanset <- tm_map(corpus, removeWords, stopwords('english'))
inspect(cleanset[1:10])
cleanset <- tm_map(cleanset, stripWhitespace)
inspect(cleanset[1:10])
tdm <- TermDocumentMatrix(cleanset)
tdm
tdm <- as.matrix(tdm)
tdm[1:30,1:5]
r_sum <- rowSums(tdm)
r_sum <- subset(r_sum, r_sum>= 20)
barplot(colSums(r_sum))

library(syuzhet)
amz_sntmt <- get_nrc_sentiment(ngtv_words)
head(amz_sntmt)
barplot(colSums(amz_sntmt), main = "Sentiment Score for Negative Words")
