attach(LabTAT)
library(car)
colnames(LabTAT) <- c("Lab A","Lab B","Lab C","Lab D")
View(LabTAT)
shapiro.test(LabTAT$`Lab A`)
shapiro.test(LabTAT$`Lab B`)
shapiro.test(LabTAT$`Lab C`)
shapiro.test(LabTAT$`Lab D`)
Stack_data <- stack(LabTAT)
View(Stack_data)
bartlett.test(values~ind, data = Stack_data)
Anova_results <- aov(values~ind, data = Stack_data)
summary(Anova_results)
