attach(Cutlets)
shapiro.test(Unit.A)
shapiro.test(Unit.B)
library(car)
names(Cutlets) <- c("UnitA","UnitB")
View(Cutlets)
Stacked_Data <- stack(Cutlets)
View(Stacked_Data)
attach(Stacked_Data)
library(car)
bartlett.test(values~ind, data = Stacked_Data)
nova_results <- aov(values~ind,data = Stacked_Data)
summary(nova_results)
