library(readxl)
library(car)
Buyer_ratio <- read.csv(file.choose())
View(Buyer_ratio)
attach(Buyer_ratio)
shapiro.test(`East`)
shapiro.test(`West`)
shapiro.test(`North`)
shapiro.test(`South`)

stack_data <- stack(Buyer_ratio)
View(stack_data)
bartlett.test(values~ind, data = stack_data)
Anova_res <- aov(values~ind, data = stack_data)
summary(Anova_res)
